### ISSUE TITLE
Successfully installed but keep having error

### ISSUE THREAD

**Issue by hiudkny** [phyletica/sumcoevolity#1]
Hi,

Sorry, i'm trying to use pycoevolity for my species group but keep having error after successfully installing. When install the python package, instead of 'python setup.py install' I used 'python3 setup.py install'.  There was no error after installation. However, when I tried to run it, I kept having this error:
Traceback (most recent call last):
  File "/home/lizard/.local/bin/pyco-sumchains", line 11, in <module>
    load_entry_point('pycoevolity==0.2.4', 'console_scripts', 'pyco-sumchains')()
  File "/home/lizard/.local/lib/python3.6/site-packages/pycoevolity/cli/sumchains.py", line 14, in main
    pycoevolity.write_splash(sys.stderr)
  File "/home/lizard/.local/lib/python3.6/site-packages/pycoevolity/__init__.py", line 96, in write_splash
    stream.write("{0:^{1}}\n".format(__project__.capitalize(), w))
NameError: name '__project__' is not defined
Can you help me with this error? Thanks a lot :)

Hung.

**Comment by joaks1** [comment]
Hello,

Thanks for catching this. I had recently updated how the project metadata gets stored and used by the setup/installation process and the project itself, and I introduced an import error that led to the problem you are experiencing. Commit 67712233 fixes this error.  I also released Version 0.2.5 with this fix. If you pull or clone the most recent version of the repository it should work. Or if you installed with pip, you can update the package using:

    pip install git+git://github.com/phyletica/pycoevolity.git --upgrade

I'm going to close this issue, but please reopen it if the updates don't fix the problem for you (or open a new issue if you run into another problem).

All the best,

Jamie
